inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'test/test_helper.rb'

Metrics/BlockLength:
  Max: 264

Metrics/ModuleLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  Max: 30 # default is 10

LineLength:
  Max: 150
